# Generated by Django 4.2.4 on 2023-08-14 11:59

import datas.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', datas.models.CustomAutoField(primary_key=True, serialize=False)),
                ('card', models.CharField(blank=True, max_length=20, null=True, verbose_name='카드명')),
                ('brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='회사명')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
                ('cate', models.CharField(blank=True, max_length=30, null=True, verbose_name='카드유형')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('mylist_count', models.IntegerField(default=0, verbose_name='담긴수')),
                ('fee1', models.CharField(blank=True, max_length=30, null=True, verbose_name='연회비1')),
                ('fee2', models.CharField(blank=True, max_length=30, null=True, verbose_name='연회비2')),
                ('pre_perform', models.CharField(blank=True, max_length=30, null=True, verbose_name='전월실적')),
                ('bnf1', models.CharField(blank=True, max_length=30, null=True, verbose_name='주요혜택1')),
                ('bnf2', models.CharField(blank=True, max_length=30, null=True, verbose_name='주요혜택2')),
                ('bnf3', models.CharField(blank=True, max_length=30, null=True, verbose_name='주요혜택3')),
                ('link_url', models.CharField(blank=True, max_length=60, null=True, verbose_name='상세링크')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', datas.models.CustomAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=5, null=True, verbose_name='혜택카테고리')),
                ('category_code', models.IntegerField(blank=True, null=True, verbose_name='카테고리코드')),
                ('content', models.CharField(blank=True, max_length=60, null=True, verbose_name='혜택내용')),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datas.card', verbose_name='카드번호')),
            ],
        ),
    ]
