# Generated by Django 4.2.4 on 2023-08-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_alter_benefit_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='content',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='혜택내용'),
        ),
        migrations.AlterField(
            model_name='card',
            name='link_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='상세링크'),
        ),
    ]
